<a href="https://colab.research.google.com/github/clanmaster/HavProject1/blob/master/NumpyTesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [3]:
import numpy as np

a = np.array([1,2,3])
print(a)

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]], dtype="S")
print(b)
b.sort()






[1 2 3]
[[b'9.0' b'8.0' b'7.0']
 [b'6.0' b'5.0' b'4.0']]


In [ ]:
import numpy as np
#arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])
#for x in np.nditer(arr):
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

for x in np.nditer(arr[:, ::3]):
  print(x)


1
4
6
9


###This a test of numpy library


In [4]:
import numpy as np
arr = np.array([[[[1,2,3,4],[5,6,7,8,],[9,10,11,12],[13,14,15,16,]]]])
for idx, x in np.ndenumerate(arr):
  
  print(idx,x)

(0, 0, 0, 0) 1
(0, 0, 0, 1) 2
(0, 0, 0, 2) 3
(0, 0, 0, 3) 4
(0, 0, 1, 0) 5
(0, 0, 1, 1) 6
(0, 0, 1, 2) 7
(0, 0, 1, 3) 8
(0, 0, 2, 0) 9
(0, 0, 2, 1) 10
(0, 0, 2, 2) 11
(0, 0, 2, 3) 12
(0, 0, 3, 0) 13
(0, 0, 3, 1) 14
(0, 0, 3, 2) 15
(0, 0, 3, 3) 16


On going teachings of Numpy

---



---





In [ ]:
import numpy as np
a = np.ones([2,3])
print(a)

b = np.full((3,2),2)
print (b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats



array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

v1 = np.array([[1,2,3]])
v2 = np.array([[6,7,8]])

arr = np.concatenate((v1,v2))
print(arr)


[[1 2 3]
 [6 7 8]]


In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])#scaler, vector, matrix
print(arr.shape)




(1, 3, 4)


In [ ]:
a = 0
while a < 10:
  if a %2 == 1:
    print(str(a) + ' is odd')
  else:
    print(str(a) + ' is even')

  a += 1

0 is even
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [ ]:
import numpy as np
arr = np.array([2,3,4,5,6,7,8,9,20])

slickArr = np.array_split(arr,3)
print(slickArr)


[array([2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 20])]


##Misc code practice

In [ ]:
start = 4
stop = 20###this variable needs to be larger then the start variable.
step = 2
xs = list(range(10))
print(xs[start:stop:step])


[4, 6, 8]


In [ ]:
import numpy as np

arr = np.array([50,55,56,57,58])
filter_arr = []
for element in arr:
  if element > 65:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, False, False, False]
[]
